---
# tasks file for jenkins
- name: Update apt-cache
  apt:
    name: openjdk-"{{ version }}"-jre
    state: present
    update_cache: yes
      
- name: Add Jenkins repository key
  shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      
- name: Add Jenkins repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    state: present
      
- name: Install Jenkins
  apt:
    name: jenkins
    state: present
      
- name: Start and enable Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Generate an SSH key pair
  openssh_keypair:
    path: /tmp/id_rsa
    type: rsa
    size: 2048
    state: present